name: CommandWork
main: com.karusmc.commandwork.plugin.CommandWork
version: 2.0.1
description: CommandWork lib
website: https://github.com/Pante/CommandWork
author: PanteLegacy

commands:

  commandwork:
    aliases: [commandwork, cwork, commandw, cmdwork, cw]
    description: Base commandwork command
    usage: /commandwork [subcommand]
    permission: commandwork.main
    
  "commandwork about":
    aliases: [a]
    description: About subcommand
    usage: /commandwork about
    permission: commandwork.about
    
  "commandwork help":
    aliases: [h]
    description: Help subcommand
    usage: /commandwork help
    permission: commandwork.help
    
  "commandwork invalid":
    aliases: [invalid, i]
    description: Invalid Subcommand
    usage: /commadwork invalid
    permission: commandwork.invalid